In [285]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
# can also be passed as a tuple or any array-like object
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [286]:
# version of numpy

print(np.__version__)

1.18.4


In [287]:
new_arr = np.array(42) # 0-D array, basically just the value
print(new_arr)
# 1-D array is a normal array

42


In [288]:
# 2-D

two_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(two_arr)

[[1 2 3]
 [4 5 6]]


In [289]:
# 3-D basically just two 2-D arrays
third_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(third_arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [290]:
# Number of dimension
print(arr.ndim)
print(two_arr.ndim)
print(third_arr.ndim)

1
2
3


In [291]:
# 5-D or more

big_arr = np.array([1, 2, 3, 4], ndmin=5)

print(big_arr)
print("Num of dimensions: ", big_arr.ndim)

[[[[[1 2 3 4]]]]]
Num of dimensions:  5


In [292]:
print(third_arr[0, 0, 1] + third_arr[1, 0, 1])

4


In [293]:
# Slicing

print(arr[1:5:2]) # [start:end:step]

print(two_arr[1, 1:4]) # second array index 1 to 4 excluding 4
print(two_arr[0:2, 2]) # index 2 from both elements

[2 4]
[5 6]
[3 6]


In [294]:
# Data type

print(arr.dtype)

int64


In [295]:
# Setting the datatype

anotha_arr = np.array([1, 2, 3, 4], dtype='S')
print(anotha_arr)
print(anotha_arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [296]:
# Converting data types

float_arr = np.array([1.1, 2.1, 3.1])
diff_arr = float_arr.astype('i')

print(diff_arr)
print(diff_arr.dtype)

random_arr = np.array([1, 0, 3])
bool_arr = random_arr.astype(bool)

print(bool_arr)
print(bool_arr.dtype)

[1 2 3]
int32
[ True False  True]
bool


In [297]:
# Copying array

x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [298]:
# Shape

print(arr.shape)
print(two_arr.shape)
print(big_arr.shape)

(5,)
(2, 3)
(1, 1, 1, 1, 4)


In [299]:
# Reshaping
# Multiplying numbers together should equal total length
# It's a view
# Putting -1 will let Numpy calculate dimension for you

long_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

half_arr = long_arr.reshape(4, 3)
print(half_arr)
print(half_arr.shape)

third_arr = long_arr.reshape(2, 3, -1)
print(third_arr.base)
print(third_arr.shape)

flat_arr = third_arr.reshape(-1)
print(flat_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(2, 3, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
